import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.css"
import Header from "@/components/shared/Header"
import Footer from "@/components/shared/Footer"
import { EdgeStoreProvider } from "@/lib/edgestore"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Evently",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/icons/logo-grey.svg",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="">
          <Header />
          <div>
            <EdgeStoreProvider>{children}</EdgeStoreProvider>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  )
}
